apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ printf "%s-%s" .Release.Name .Chart.Name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jenkins
  template:
    metadata:
      labels:
        app: jenkins
    spec:
      containers:
      - name: jenkins
        image: {{ printf "%s:%s" .Values.image.repository .Values.image.tag }}
        env: 
          - name: JENKINS_USERNAME
            value: {{ default "test" .Values.jenkinsUsername.value | quote}}
          - name: JENKINS_PASSWORD
            {{- if .Values.jenkinsPassword.value }}
            value: {{ .Values.jenkinsPassword.value }}
            {{- else }}
            value: testPassword
            {{- end }}
        ports:
          - name: {{ .Values.containerPorts.name }}
            containerPort: 8080
        volumeMounts:
        - name: jenkins-home
          mountPath: /var/jenkins_home
      volumes:
      - name: jenkins-home
        emptyDir: { }