apiVersion: v1
kind: Service
metadata:
  name: {{- template "samplechart.fullname" . -}}
spec:
  type: {{ .Values.service.type }}
  ports:
  - port: 8080
    targetPort: 8080
    nodePort: {{ .Values.service.nodePort}}
  selector:
    app: jenkins